---
name: Rolling release

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - id: app-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          repositories: |
            client-go
            authentik
      - id: get-user-id
        name: Get GitHub app user ID
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          path: client-go
      - name: Fetch schema
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: goauthentik/authentik
          token: "${{ steps.app-token.outputs.token }}"
          ref: main
          path: authentik
      - id: changes
        name: Check for changes
        working-directory: client-go
        run: |
          cp ../authentik/schema.yml schema.yml
          if git diff --exit-code -- schema.yml > /dev/null; then
            echo "schema_has_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "schema_has_changes=true" >> "$GITHUB_OUTPUT"
          fi
      - id: publish
        name: Publish to GitHub
        if: "${{ steps.changes.outputs.schema_has_changes == 'true' }}"
        working-directory: client-go
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          version="3.$(yq -r '.info.version' schema.yml)-$(date +%s)"
          make version="$version"

          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

          git add .
          git commit -F "diff.test" || exit 0
          git tag "v$version"
          git push
          git push --tags
          truncate -s '<125000' diff.test
          gh release create "v$version" -F diff.test --prerelease

          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Update in main repo
        if: "${{ steps.changes.outputs.schema_has_changes == 'true' }}"
        working-directory: authentik
        run: |
          go get 'goauthentik.io/api/v3@v${{ steps.publish.outputs.version }}'
      - id: create-pull-request
        name: Create pull request in main repo
        if: "${{ steps.changes.outputs.schema_has_changes == 'true' }}"
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          path: authentik
          token: "${{ steps.app-token.outputs.token }}"
          branch: deps/bump-client-go
          commit-message: "core: bump goauthentik.io/api/v3 to ${{ steps.publish.outputs.version }}"
          title: "core: bump goauthentik.io/api/v3 to ${{ steps.publish.outputs.version }}"
          delete-branch: true
          signoff: true
          author: "${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"
          labels: dependencies
      - name: Enable pull request auto-merge
        if: "${{ steps.changes.outputs.schema_has_changes == 'true' }}"
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          token: "${{ steps.app-token.outputs.token }}"
          pull-request-number: "${{ steps.create-pull-request.outputs.pull-request-number }}"
          merge-method: squash
